### ISSUE TITLE
gic_dist_map define error, not work

### ISSUE THREAD

**Issue by lydmcu** [SEL4PROJ/seL4_projects_libs#11]
truct gic_dist_map {
    uint32_t enable;                                    /* 0x000 */
    uint32_t ic_type;                                   /* 0x004 */
    uint32_t dist_ident;                                /* 0x008 */

    uint32_t res1[29];                                  /* [0x00C, 0x080) */

    uint32_t irq_group0[CONFIG_MAX_NUM_NODES];          /* [0x080, 0x84) */
    uint32_t irq_group[31];                             /* [0x084, 0x100) */
    uint32_t enable_set0[CONFIG_MAX_NUM_NODES];         /* [0x100, 0x104) */
    uint32_t enable_set[31];   

irq_group0, enable_set0 is not mean work muti core, this will not work OK
for examp:
      For interrupt ID m, when DIV and MOD are the integer division and modulo operations:
      the corresponding GICD_ISENABLER number, n, is given by n = m DIV 32
      the offset of the required GICD_ISENABLER is (0x100 + (4*n))
      the bit number of the required Set-enable bit in this register is m MOD 32.

**Comment by lydmcu** [comment]
if CONFIG_MAX_NUM_NODES > 1, the other offset is not write, enable_set0 is banked

**Comment by lydmcu** [comment]
I am sorry, I not really undstand the virtual gcid at the very start, it is OK.

**Comment by kent-mcleod** [comment]
@lydmcu no problem.  It's still helpful having the extra eyes go over the implementations.
